### PR TITLE
fix: support resource directories in external Swift packages

### LINKED ISSUE #308: How to specify resource folder?
Is there any way to specify the resources folder? I have the following in the Package.swift file
`resources: [.process("Resources")]`
This works in SPM but does not work in bazel

### PR DESCRIPTION
**Pull request by cgrindel**
- Provide more robust resource bundle `Info.plist`. Thanks to @tingyao-ui 
- For resource directories specified in `Package.swift` files, be sure to `glob()` their contents when defining `apple_resource_bundle`. Thanks to @denis15yo.
- Add `resources_example` that exercises this functionality.
- Fix bug with reading `Package.resolved` for `Package.swift` that have no pinned packages (e.g., only contains local Swift packages).
- Extract and use the default localization if it is specified in the `Package.swift`.

Closes #308.

### CODE REVIEW

**Review by tingyao-ui — APPROVED** [review]
LGTM

**Comment by yume190** [comment]
## examples/resources_example

### third_party/package_with_resources/Package.swift

```swift
.target(
    name: "CoolUI",
    resources: [.process("Resources")]
),
```

### BUILD

```python
apple_resource_bundle(
    name = "Sources_CoolUI_resource_bundle",
    bundle_name = "Sources_CoolUI_resource_bundle",
    infoplists = [":Sources_CoolUI_resource_bundle_infoplist"],
    resources = glob(["Sources/CoolUI/Resources/**"]),
)
```

### Origin Resouces

```sh
tree third_party/package_with_resources/Sources/CoolUI/Resources
third_party/package_with_resources/Sources/CoolUI/Resources
├── Assets.xcassets
│   ├── Contents.json
│   └── avatar.imageset
│       ├── Contents.json
│       └── ai_chatbot_avatar.pdf
└── Localization
    └── en.lproj
        └── Localizable.strings
```

### App Resouces

```sh
tree bazel-bin/Sources/MyApp/Payload/iosapp.app/Sources_CoolUI_resource_bundle.bundle
bazel-bin/Sources/MyApp/Payload/iosapp.app/Sources_CoolUI_resource_bundle.bundle
├── Assets.car
├── Info.plist
└── en.lproj
    └── Localizable.strings
```

**Comment by yume190** [comment]
## My test

### Resources Folder

```sh
tree Sources/Target/Resources
Sources/Target/Resources
├── Assets.xcassets
│   ├── Contents.json
│   └── avatar.imageset
│       ├── Contents.json
│       └── ai_chatbot_avatar.pdf
└── Localization
    ├── en.lproj
    │   └── Localizable.strings
    └── fr.lproj
        └── Localizable.strings
```

```python
folder = 'Sources/Target/Resources'
```        

### Flat

```python
apple_resource_bundle(
    name = "bundle_flat",
    bundle_name = "Flatten",
    resources = glob([
        folder + "/**",
    ], exclude = [
        "**/.DS_Store"
    ],),
)
```

```sh
Flatten.bundle
├── Assets.car
├── en.lproj
│   └── Localizable.strings
└── fr.lproj
    └── Localizable.strings
```

### Structured

```python
apple_resource_bundle(
    name = "bundle_structured",
    bundle_name = "Structured",
    structured_resources = glob([
        folder + "/**",
    ]),
)
```

```sh
Structured.bundle
└── Sources
    └── Target
        └── Resources
            ├── Assets.xcassets
            │   ├── Contents.json
            │   └── avatar.imageset
            │       ├── Contents.json
            │       └── ai_chatbot_avatar.pdf
            └── Localization
                ├── en.lproj
                │   └── Localizable.strings
                └── fr.lproj
                    └── Localizable.strings
```

### Folder

```python
apple_resource_bundle(
    name = "bundle_folder",
    bundle_name = "folder",
    resources = [
        folder + "/Assets.xcassets",
        folder + "/Localization",
    ],
)
```

```sh
folder.bundle
├── Assets.xcassets
│   ├── Contents.json
│   └── avatar.imageset
│       ├── Contents.json
│       └── ai_chatbot_avatar.pdf
└── Localization
    ├── en.lproj
    │   └── Localizable.strings
    └── fr.lproj
        └── Localizable.strings
```

**Comment by yume190** [comment]
## Flat

```sh
tree Sources/res
Sources/res
├── a.txt
└── b
    ├── b.txt
    └── c
        └── c.txt
```

```python
group = 'Sources/res'
apple_resource_group(
    name = "group_flat",
    resources = glob([
        group + "/**",
    ]),
)
```

```sh
Example.app
└── Contents
    ├── Info.plist
    ├── MacOS
    │   └── Example
    ├── PkgInfo
    ├── Resources
    │   ├── a.txt
    │   ├── b.txt
    │   └── c.txt
    └── _CodeSignature
        └── CodeResources
```

**Review by denis15yo — APPROVED** [review]

**Pull request merged**
